# Generated by Django 3.2.3 on 2021-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_world_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='current_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='city',
            name='time_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
