# Generated by Django 3.2.3 on 2021-06-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_world_time', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='time_offset',
            new_name='offset',
        ),
    ]
