# Generated by Django 3.2.3 on 2021-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_world_time', '0002_auto_20210519_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='time_offset',
            field=models.IntegerField(default=0),
        ),
    ]
