# Generated by Django 3.2.3 on 2021-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=64)),
                ('body', models.TextField(max_length=1024)),
                ('author', models.TextField(max_length=32)),
            ],
        ),
    ]
